version: '3.8'

services:
  mysqldb:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "test_db"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
    ports:
      - "9906:3306"

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    links:
      - mysqldb
    environment:
      PMA_HOST: "mysqldb"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "test_db"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
    restart: always
    ports:
      - "8081:80"
    volumes:
      - mysql-data:/var/lib/mysql

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: dockeruser
      POSTGRES_PASSWORD: dockerpassword
      POSTGRES_DB: dockerdb
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: master@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Master@123
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dockerdb
      SPRING_DATASOURCE_USERNAME: dockeruser
      SPRING_DATASOURCE_PASSWORD: dockerpassword

volumes:
  postgres-data:
  pgadmin-data:
  mysql-data: