server:
  port: 8080
spring:
  profiles.actives: "dev"
  postgresql-datasource:
    jdbc-url: jdbc:postgresql://postgresql:5432/dockerdb
    username: dockeruser
    password: dockerpassword
    driver-class-name: org.postgresql.Driver

  mysql-datasource:
    jdbc-url: jdbc:mysql://mysqldb:9906/test_db
    username: USER
    password: PASS
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop




connection:
  username: admin
  remoteAddress: 192.168.1.1

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    env:
      show-values: always