server:
  port: 8080
spring:
  profiles.actives: "dev"
  postgresql-datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/springboot_db
    #url: jdbc:postgresql://localhost:5432/springboot_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  mysql-datasource:
    #jdbc-url: jdbc:mysql://mysql:9906/mysql_db
    #url: jdbc:mysql://localhost:9906/mysql_db
    jdbc-url: jdbc:mysql://localhost:9906/php-app
    username: USER
    password: PASS
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop




connection:
  username: admin
  remoteAddress: 192.168.1.1

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    env:
      show-values: always